<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\LibraryDDD.Application\LibraryDDD.Application.csproj" />
    <ProjectReference Include="..\LibraryDDD.Infrastructure\LibraryDDD.Infrastructure.csproj" />
    <ProjectReference Include="..\LibraryDDD.Domain\LibraryDDD.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Endpoints\" />
    <Folder Include="Responses\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
